# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.75.0
    hooks:
    - id: terraform_fmt
    # - id: terraform_docs
    # - id: terraform_tflint
    # - id: terraform_tfsec
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-yaml
      - id: check-added-large-files
